source 'https://rubygems.org'

gem 'nokogiri', '1.6.1'
gem 'rake', '10.1.1'
gem 'activesupport', '3.0.0'
gem 'i18n', '0.6.9'

group :development, :test do
  gem 'rspec',  '2.14.1'
  gem 'yarjuf', '1.0.5'
  gem 'fakefs', require: 'fakefs/safe'
end
